### ISSUE TITLE
Use `const` when possible

### ISSUE THREAD

**Issue by karlhorky** [julialearnscoding/random-color-cli#1]
Some variable declarations could use `const` instead of `var` or `let`:

https://github.com/julialearnscoding/random-color-cli/blob/25c5c9c12d3e6a261a4ce58fe22ea258cde5b630/rainbow.js#L1-L10

This will make sure that the variables aren't accidentally reassigned.

**Comment by julialearnscoding** [comment]
this is fixed in daf15e8

**Comment by karlhorky** [comment]
Sweet, nice one! 🙌🎉
